export type ALL_VERSION_KEYS =
  | GENERAL_COMPONENT
  | GENERAL_TABLES
  | COURSES_COMPONENT
  | COURSE_COMPONENT
  | COURSE_DETAIL_COMPONENT
  | ASK_QUESTION_POPOVER_COMPONENT
  | NAV_INSTRUCTOR_MENU_COMPONENT
  | INSTRUCTOR_COURSES_COMPONENT
  | INSTRUCTOR_COURSE_LECTURES_COMPONENT
  | LECTURE_SEARCH_AND_SORT_COMPONENT
  | LIVE_PRESENTATION_QUESTIONS_COMPONENT
  | COURSE_ENGAGEMENT_COMPONENT
  | COURSE_ANALYTICS_COMPONENT
  | COURSE_ANALYTICS_TRENDS_COMPONENT
  | COURSE_PARTICIPANTS_COMPONENT
  | DEPARTMENT_COURSE_PARTICIPANT_COMPONENT
  | PARTICIPANT_OVERVIEW_COMPONENT
  | NAV_ADMIN_MENU_COMPONENT
  | DEPARTMENTS_COMPONENT
  | ARBITRARY_GROUP_LAYOUT_COMPONENT
  | ARBITRARY_GROUP_DETAIL_COMPONENT
  | ARBITRARY_GROUP_COURSES_COMPONENT
  | ADD_COURSE_POPOVER_COMPONENT
  | DEPARTMENT_EDIT_DEPARTMENT_COMPONENT
  | EDIT_PARTICIPANTS_COMPONENT
  | INSTRUCTOR_LECTURE_REVIEWER_COMPONENT
  | INSTRUCTOR_PRESENTATION_PLAYBACK_CONTROLS_COMPONENT
  | POLL_REVIEWER_COMPONENT
  | LECTURE_ENGAGEMENT_COMPONENT
  | LECTURE_RENAME_POPUP_COMPONENT
  | LECTURE_REVIEWER_COMPONENT
  | COURSE_ENGAGEMENT_TRENDS_COMPONENT
  | GROUP_ENGAGEMENT_TRENDS_COMPONENT
  | GROUP_ENGAGEMENT_COMPONENT
  | ADD_EMAIL_POPOVER_COMPONENT
  | LECTURE_DETAIL_COMPONENT
  | EDIT_PERIOD_DIALOG_COMPONENT
  | GROUP_ANALYTICS_COMPONENT
  | GROUPS_VIEW_COMPONENT
  | LECTURE_STOP_BUTTON_COMPONENT
  | LECTURE_ANALYTICS
  | CUSTOM_SECURITY_APP_ERRORS
  | SECURITY_OVERLAY
  | ANALYTICS_TOGGLE
  | SERIES_DOCUMENTS
  | COURSE_SECURITY_EVENTS;

export enum GENERAL_COMPONENT {
  'STUDENT_COURSES_PARTICIPANT_MEETINGS' = 'GENERAL_COMPONENT.STUDENT_COURSES_PARTICIPANT_MEETINGS',
  'INSTRUCTOR_PRESENTER' = 'GENERAL_COMPONENT.INSTRUCTOR_PRESENTER',
  'INSTRUCTORS_PRESENTERS' = 'GENERAL_COMPONENT.INSTRUCTORS_PRESENTERS',
  'ADD_INSTRUCTOR_PRESENTER' = 'GENERAL_COMPONENT.ADD_INSTRUCTOR_PRESENTER',
  'STUDENT_PARTICIPANT' = 'GENERAL_COMPONENT.STUDENT_PARTICIPANT',
  'STUDENTS_PARTICIPANTS' = 'GENERAL_COMPONENT.STUDENTS_PARTICIPANTS',
  'REGISTERED_PARTICIPANTS' = 'GENERAL_COMPONENT.REGISTERED_STUDENTS_PARTICIPANTS',
  'UNREGISTERED_PARTICIPANTS' = 'GENERAL_COMPONENT.UNREGISTERED_STUDENTS_PARTICIPANTS',
  'OBSERVER' = 'GENERAL_COMPONENT.OBSERVER',
  'VIEWER' = 'GENERAL_COMPONENT.VIEWER',
  'DISTROLIST_INVITATIONS' = 'GENERAL_COMPONENT.DISTROLIST_INVITATIONS',
  'ADD_STUDENT_PARTICIPANT' = 'GENERAL_COMPONENT.ADD_STUDENT_PARTICIPANT',
  'COURSE_MEETING' = 'GENERAL_COMPONENT.COURSE_MEETING',
  'COURSES_MEETINGS' = 'GENERAL_COMPONENT.COURSES_MEETINGS',
  'NO_COURSES_MEETINGS' = 'GENERAL_COMPONENT.NO_COURSES_MEETINGS',
  'ALL_COURSES_MEETINGS' = 'GENERAL_COMPONENT.ALL_COURSES_MEETINGS',
  'TOP_COURSES_MEETINGS' = 'GENERAL_COMPONENT.TOP_COURSES_MEETINGS',
  'COURSE_MEETING_GROUPS' = 'GENERAL_COMPONENT.COURSE_MEETING_GROUPS',
  'COURSE_MEETING_NAME' = 'GENERAL_COMPONENT.COURSE_MEETING_NAME',
  'LECTURE_PRESENTATION' = 'GENERAL_COMPONENT.LECTURE_PRESENTATION',
  'LECTURES_PRESENTATIONS' = 'GENERAL_COMPONENT.LECTURES_PRESENTATIONS',
  'UNNAMED_LECTURE_PRESENTATION' = 'GENERAL_COMPONENT.UNNAMED_LECTURE_PRESENTATION',
  'QUESTIONS' = 'GENERAL_COMPONENT.QUESTIONS',
  'STUDENT_PARTICIPANT_QUESTIONS' = 'GENERAL_COMPONENT.STUDENT_PARTICIPANT_QUESTIONS',
  'ERROR_STUDENT_PARTICIPANT_QUESTIONS' = 'GENERAL_COMPONENT.ERROR_STUDENT_PARTICIPANT_QUESTIONS',
  'LOADING_STUDENT_PARTICIPANT_QUESTIONS' = 'GENERAL_COMPONENT.LOADING_STUDENT_PARTICIPANT_QUESTIONS',
  'NONE_STUDENT_PARTICIPANT_QUESTIONS' = 'GENERAL_COMPONENT.NONE_STUDENT_PARTICIPANT_QUESTIONS',
  'DEPARTMENT' = 'GENERAL_COMPONENT.DEPARTMENT',
  'DEPARTMENTS' = 'GENERAL_COMPONENT.DEPARTMENTS',
  'LOADING_LECTURES_PRESENTATIONS' = 'GENERAL_COMPONENT.LOADING_LECTURES_PRESENTATIONS',
  'ERROR_LECTURES_PRESENTATIONS' = 'GENERAL_COMPONENT.ERROR_LECTURES_PRESENTATIONS',
  'NONE_LECTURES_PRESENTATIONS_COURSE_MEETING' = 'GENERAL_COMPONENT.NONE_LECTURES_PRESENTATIONS_COURSE_MEETING',
  'NO_PRESENTATION_LECTURE_PRESENTATION' = 'GENERAL_COMPONENT.NO_PRESENTATION_LECTURE_PRESENTATION',
  'LOADING_COURSE_MEETING' = 'GENERAL_COMPONENT.LOADING_COURSE_MEETING',
  'LOADING_COURSES_MEETINGS' = 'GENERAL_COMPONENT.LOADING_COURSES_MEETINGS',
  'ERROR_COURSE_MEETING' = 'GENERAL_COMPONENT.ERROR_COURSE_MEETING',
  'ERROR_COURSES_MEETINGS' = 'GENERAL_COMPONENT.ERROR_COURSES_MEETINGS',
  'NO_PARTICIPATION' = 'GENERAL_COMPONENT.NO_PARTICIPATION',
  'PARTICIPATION_PRESENTATION_DESCRIPTION' = 'GENERAL_COMPONENT.PARTICIPATION_PRESENTATION_DESCRIPTION',
  'PARTICIPATION_PRESENTATIONS_DESCRIPTION' = 'GENERAL_COMPONENT.PARTICIPATION_PRESENTATIONS_DESCRIPTION',
  'ENGAGEMENT_PRESENTATION_DESCRIPTION' = 'GENERAL_COMPONENT.ENGAGEMENT_PRESENTATION_DESCRIPTION',
  'ENGAGEMENT_PRESENTATIONS_DESCRIPTION' = 'GENERAL_COMPONENT.ENGAGEMENT_PRESENTATIONS_DESCRIPTION',
  'UPDATING_COURSE_MEETING' = 'GENERAL_COMPONENT.UPDATING_COURSE_MEETING',
  'NO_QUESTIONS_LECTURE_PRESENTATION' = 'GENERAL_COMPONENT.NO_QUESTIONS_LECTURE_PRESENTATION',
  'NO_QUESTIONS_COURSE_MEETING' = 'GENERAL_COMPONENT.NO_QUESTIONS_COURSE_MEETING',
  'QUESTIONS_COURSE_MEETING_ERROR' = 'GENERAL_COMPONENT.QUESTIONS_COURSE_MEETING_ERROR',
  'POLL_SEGMENT' = 'GENERAL_COMPONENT.POLL_SEGMENT',
  'LOADING_SEGMENT_POLL' = 'GENERAL_COMPONENT.LOADING_SEGMENT_POLL',
  'NO_POLL_QUESTION_SEGMENT' = 'GENERAL_COMPONENT.NO_POLL_QUESTION_SEGMENT',
  'POLL_VISUALIZATION_SEGMENT' = 'GENERAL_COMPONENT.POLL_VISUALIZATION_SEGMENT',
  'POLL_PRESENTATION_DESCRIPTION' = 'GENERAL_COMPONENT.POLL_PRESENTATION_DESCRIPTION',
  'POLL_PRESENTATIONS_DESCRIPTION' = 'GENERAL_COMPONENT.POLL_PRESENTATIONS_DESCRIPTION',
  'YOUR_COURSE_MEETING_PARTICIPATION' = 'GENERAL_COMPONENT.YOUR_COURSE_MEETING_PARTICIPATION',
  'COURSE_MEETING_PARTICIPATION' = 'GENERAL_COMPONENT.COURSE_MEETING_PARTICIPATION',
  'SEGMENT' = 'GENERAL_COMPONENT.SEGMENT',
  'SEGMENTS' = 'GENERAL_COMPONENT.SEGMENTS',
  'START' = 'GENERAL_COMPONENT.START',
  'END' = 'GENERAL_COMPONENT.END',
  'DOCUMENTS' = 'GENERAL_COMPONENT.DOCUMENTS',
  'DOCUMENT' = 'GENERAL_COMPONENT.DOCUMENT',
}

export enum GENERAL_TABLES {
  'COURSE_MEETING_PARTICIPATION' = 'GENERAL_TABLES.COURSE_MEETING_PARTICIPATION',
  'LECTURE_PRESENTATION_PARTICIPATION' = 'GENERAL_TABLES.LECTURE_PRESENTATION_PARTICIPATION',
  'LECTURES_PRESENTATIONS_VIEWED' = 'GENERAL_TABLES.LECTURES_PRESENTATIONS_VIEWED',
  'NOT_YET_IN_COURSE_MEETING' = 'GENERAL_TABLES.NOT_YET_IN_COURSE_MEETING',
}

export enum COURSES_COMPONENT {
  'TITLE' = 'COURSES_COMPONENT.TITLE',
  'CURRENT' = 'COURSES_COMPONENT.CURRENT',
  'UPCOMING' = 'COURSES_COMPONENT.UPCOMING',
  'PREVIOUS' = 'COURSES_COMPONENT.PREVIOUS',
  'UNREGISTERED' = 'COURSES_COMPONENT.UNREGISTERED',
}

export enum COURSE_COMPONENT {
  'MENU_OVERVIEW' = 'COURSE_COMPONENT.MENU_OVERVIEW',
  'MENU_LECTURES_PRESENTATIONS' = 'COURSE_COMPONENT.MENU_LECTURES_PRESENTATIONS',
}

export enum COURSE_DETAIL_COMPONENT {
  'TITLE' = 'COURSE_DETAIL_COMPONENT.TITLE',
  'LECTURES_LOADING' = 'COURSE_DETAIL_COMPONENT.LECTURES_LOADING',
  'LECTURES_ERROR' = 'COURSE_DETAIL_COMPONENT.LECTURES_ERROR',
  'OVERVIEW_ERROR' = 'COURSE_DETAIL_COMPONENT.ERROR',
  'NO_OVERVIEW' = 'COURSE_DETAIL_COMPONENT.NO_OVERVIEW',
}

export enum ASK_QUESTION_POPOVER_COMPONENT {
  'UNSEEN_QUESTION' = 'ASK_QUESTION_POPOVER_COMPONENT.UNSEEN_QUESTION',
  'QUESTION_COURSE_MEETING' = 'ASK_QUESTION_POPOVER_COMPONENT.QUESTION_COURSE_MEETING',
  'QUESTION_LECTURE_PRESENTATION' = 'ASK_QUESTION_POPOVER_COMPONENT.QUESTION_LECTURE_PRESENTATION',
  'QUESTION_SEGMENT' = 'ASK_QUESTION_POPOVER_COMPONENT.QUESTION_SEGMENT',
}

export enum NAV_INSTRUCTOR_MENU_COMPONENT {
  'INSTRUCTOR_PRESENTER_TOOLS' = 'NAV_INSTRUCTOR_MENU_COMPONENT.INSTRUCTOR_PRESENTER_TOOLS',
  'COURSE_MEETING_MANAGEMENT' = 'NAV_INSTRUCTOR_MENU_COMPONENT.COURSE_MEETING_MANAGEMENT',
}

export enum INSTRUCTOR_COURSES_COMPONENT {
  'COURSE_MEETING_MANAGEMENT' = 'INSTRUCTOR_COURSES_COMPONENT.COURSE_MEETING_MANAGEMENT',
}

export enum INSTRUCTOR_COURSE_LECTURES_COMPONENT {
  'START_NEW' = 'INSTRUCTOR_COURSE_LECTURES_COMPONENT.START_NEW',
  'BROADCASTER' = 'INSTRUCTOR_COURSE_LECTURES_COMPONENT.BROADCASTER',
}

export enum LECTURE_SEARCH_AND_SORT_COMPONENT {
  'SEARCH' = 'LECTURE_SEARCH_AND_SORT_COMPONENT.SEARCH',
}

export enum LIVE_PRESENTATION_QUESTIONS_COMPONENT {
  'ANONYMITY' = 'LIVE_PRESENTATION_QUESTIONS_COMPONENT.ANONYMITY',
  'NO_QUESTIONS' = 'LIVE_PRESENTATION_QUESTIONS_COMPONENT.NO_QUESTIONS',
  'LECTURE_PRESENTATION_BEGINS' = 'LIVE_PRESENTATION_QUESTIONS_COMPONENT.LECTURE_PRESENTATION_BEGINS',
}

export enum COURSE_ENGAGEMENT_COMPONENT {
  'TITLE' = 'DEPARTMENT_COURSE_ENGAGEMENT_COMPONENT.TITLE',
  'ERROR' = 'DEPARTMENT_COURSE_ENGAGEMENT_COMPONENT.ERROR',
}

export enum COURSE_ANALYTICS_COMPONENT {
  'TITLE' = 'COURSE_ANALYTICS.TITLE',
  'LOADING' = 'COURSE_ANALYTICS.LOADING',
  'LECTURES_ERROR' = 'COURSE_ANALYTICS.LECTURES_ERROR',
  'DOCUMENTS_ERROR' = 'COURSE_ANALYTICS.DOCUMENTS_ERROR',
  'ANALYTICS_ERROR' = 'COURSE_ANALYTICS.ANALYTICS_ERROR',
  'NO_DOCUMENTS' = 'COURSE_ANALYTICS.NO_DOCUMENTS',
  'NONE' = 'COURSE_ANALYTICS.NONE',
}

export enum COURSE_ANALYTICS_TRENDS_COMPONENT {
  'TITLE' = 'COURSE_ANALYTICS_TRENDS_COMPONENT.TITLE',
  'NONE' = 'COURSE_ANALYTICS_TRENDS_COMPONENT.NONE',
}

export enum COURSE_PARTICIPANTS_COMPONENT {
  'TITLE' = 'COURSE_PARTICIPANTS_COMPONENT.TITLE',
  'LOADING' = 'COURSE_PARTICIPANTS_COMPONENT.LOADING',
  'ERROR' = 'COURSE_PARTICIPANTS_COMPONENT.ERROR',
}

export enum DEPARTMENT_COURSE_PARTICIPANT_COMPONENT {
  'REMOVE' = 'DEPARTMENT_COURSE_PARTICIPANT_COMPONENT.REMOVE',
  'PROMOTE' = 'DEPARTMENT_COURSE_PARTICIPANT_COMPONENT.PROMOTE',
}

export enum PARTICIPANT_OVERVIEW_COMPONENT {
  'ERROR' = 'PARTICIPANT_OVERVIEW_COMPONENT.ERROR',
}

export enum NAV_ADMIN_MENU_COMPONENT {
  'COURSE_MEETING_DEPT_MANAGEMENT' = 'NAV_ADMIN_MENU_COMPONENT.COURSE_MEETING_DEPT_MANAGEMENT',
}

export enum DEPARTMENTS_COMPONENT {
  'COURSES_MEETINGS_DEPTS' = 'DEPARTMENTS_COMPONENT.COURSES_MEETINGS_DEPTS',
}

export enum ARBITRARY_GROUP_LAYOUT_COMPONENT {
  'SEARCH_COURSES_MEETINGS' = 'ARBITRARY_GROUP_LAYOUT_COMPONENT.SEARCH_COURSES_MEETINGS',
}

export enum ARBITRARY_GROUP_DETAIL_COMPONENT {
  'COURSES_MEETINGS_TAB' = 'ARBITRARY_GROUP_DETAIL.COURSES_MEETINGS_TAB',
}

export enum ARBITRARY_GROUP_COURSES_COMPONENT {
  'ERROR' = 'ARBITRARY_GROUP_COURSES.ERROR',
}

export enum ADD_COURSE_POPOVER_COMPONENT {
  'BUTTON_LABEL' = 'ADD_COURSE_POPOVER_COMPONENT.BUTTON_LABEL',
  'POPOVER_TITLE' = 'ADD_COURSE_POPOVER_COMPONENT.POPOVER_TITLE',
  'PLACEHOLDER' = 'ADD_COURSE_POPOVER_COMPONENT.PLACEHOLDER',
  'ERROR_NAME' = 'ADD_COURSE_POPOVER_COMPONENT.ERROR_NAME',
  'LOADING' = 'ADD_COURSE_POPOVER_COMPONENT.LOADING',
  'ERROR_SAVING' = 'ADD_COURSE_POPOVER_COMPONENT.ERROR_SAVING',
}

export enum DEPARTMENT_EDIT_DEPARTMENT_COMPONENT {
  'SUBTITLE' = 'DEPARTMENT_EDIT_DEPARTMENT_COMPONENT.SUBTITLE',
}

export enum EDIT_PARTICIPANTS_COMPONENT {
  'TITLE_ADD' = 'EDIT_PARTICIPANTS.TITLE_ADD',
  'TITLE_EDIT' = 'EDIT_PARTICIPANTS.TITLE_EDIT',
  'NO_PARTICIPANTS' = 'EDIT_PARTICIPANTS.NO_PARTICIPANTS',
  'INVITED' = 'EDIT_PARTICIPANTS_COMPONENT.INVITED',
}

export enum INSTRUCTOR_LECTURE_REVIEWER_COMPONENT {
  'QUESTIONS_TITLE' = 'INSTRUCTOR_LECTURE_REVIEWER_COMPONENT.QUESTIONS_TITLE',
  'NO_SEGMENTS' = 'INSTRUCTOR_LECTURE_REVIEWER_COMPONENT.NO_SEGMENTS',
  'PRESENTED_SEGMENTS' = 'INSTRUCTOR_LECTURE_REVIEWER_COMPONENT.PRESENTED_SEGMENTS',
  'QUESTION_ERROR' = 'INSTRUCTOR_LECTURE_REVIEWER_COMPONENT.QUESTION_ERROR',
}

export enum INSTRUCTOR_PRESENTATION_PLAYBACK_CONTROLS_COMPONENT {
  'SHARED_AUDIO' = 'INSTRUCTOR_PRESENTATION_PLAYBACK_CONTROLS_COMPONENT.SHARED_AUDIO',
}

export enum POLL_REVIEWER_COMPONENT {
  'NOT_ENDED' = 'POLL_REVIEWER_COMPONENT.NOT_ENDED',
}

export enum LECTURE_ENGAGEMENT_COMPONENT {
  'NO_SEGMENTS' = 'LECTURE_ENGAGEMENT_COMPONENT.NO_SEGMENTS',
  'NO_POLLS' = 'LECTURE_ENGAGEMENT_COMPONENT.NO_POLLS',
  'NO_PARTICIPATION' = 'LECTURE_ENGAGEMENT_COMPONENT.NO_PARTICIPATION',
  'NON_PARTICIPATING' = 'LECTURE_ENGAGEMENT_COMPONENT.NON_PARTICIPATING',
  'NON_PARTICIPATING_TITLE' = 'LECTURE_ENGAGEMENT_COMPONENT.NON_PARTICIPATING_TITLE',
  'NOT_IN_COURSE_MEETING' = 'LECTURE_ENGAGEMENT_COMPONENT.NOT_IN_COURSE_MEETING',
  'NOT_YET_ACTIVE' = 'LECTURE_ENGAGEMENT_COMPONENT.NOT_YET_ACTIVE',
  'PARTICIPANTS' = 'LECTURE_ENGAGEMENT_COMPONENT.PARTICIPANTS',
}

export enum LECTURE_RENAME_POPUP_COMPONENT {
  'TITLE' = 'LECTURE_RENAME_POPUP_COMPONENT.TITLE',
}

export enum LECTURE_REVIEWER_COMPONENT {
  'SEGMENT_REVIEW' = 'LECTURE_REVIEWER_COMPONENT.SEGMENT_REVIEW',
  'EXPORT' = 'LECTURE_REVIEWER_COMPONENT.EXPORT',
  'EXPORT_MINE' = 'LECTURE_REVIEWER_COMPONENT.EXPORT_MINE',
}

export enum COURSE_ENGAGEMENT_TRENDS_COMPONENT {
  'NO_POLLS' = 'COURSE_ENGAGEMENT_TRENDS_COMPONENT.NO_POLLS',
}

export enum GROUP_ENGAGEMENT_TRENDS_COMPONENT {
  'TOP_COURSES_MEETINGS_ENGAGEMENT' = 'GROUP_ENGAGEMENT_TRENDS_COMPONENT.TOP_COURSES_MEETINGS_ENGAGEMENT',
  'TOP_COURSES_MEETINGS_PARTICIPATION' = 'GROUP_ENGAGEMENT_TRENDS_COMPONENT.TOP_COURSES_MEETINGS_PARTICIPATION',
  'NO_POLLS' = 'GROUP_ENGAGEMENT_TRENDS_COMPONENT.NO_POLLS',
  'TOP_COURSES_MEETINGS_POLLING' = 'GROUP_ENGAGEMENT_TRENDS_COMPONENT.TOP_COURSES_MEETINGS_POLLING',
}

export enum GROUP_ENGAGEMENT_COMPONENT {
  'ERROR' = 'GROUP_ENGAGEMENT_COMPONENT.ERROR',
  'NO_PRESENTATIONS' = 'GROUP_ENGAGEMENT_COMPONENT.NO_PRESENTATIONS',
}

export enum ADD_EMAIL_POPOVER_COMPONENT {
  'DESCRIPTION_INSTRUCTOR_PRESENTER' = 'ADD_EMAIL_POPOVER_COMPONENT.DESCRIPTION_INSTRUCTOR_PRESENTER',
  'DESCRIPTION_STUDENT_PARTICIPANT' = 'ADD_EMAIL_POPOVER_COMPONENT.DESCRIPTION_STUDENT_PARTICIPANT',
}

export enum LECTURE_DETAIL_COMPONENT {
  'TITLE' = 'LECTURE_DETAIL_COMPONENT',
  'DESCRIPTION' = 'LECTURE_DETAIL_COMPONENT.DESCRIPTION',
}

export enum EDIT_PERIOD_DIALOG_COMPONENT {
  'SELECT' = 'EDIT_PERIOD_DIALOG_COMPONENT.SELECT',
}

export enum GROUP_ANALYTICS_COMPONENT {
  'NO_PRESENTATIONS' = 'GROUP_ANALYTICS_COMPONENT.NO_PRESENTATIONS',
}

export enum GROUPS_VIEW_COMPONENT {
  'DESCRIPTION' = 'GROUPS_VIEW_COMPONENT.DESCRIPTION',
}

export enum LECTURE_STOP_BUTTON_COMPONENT {
  'END' = 'LECTURE_STOP_BUTTON.END',
  'ENDING' = 'LECTURE_STOP_BUTTON.ENDING',
}

export enum LECTURE_ANALYTICS {
  'UNIQUE_VIEWS' = 'LECTURE_ANALYTICS.UNIQUE_VIEWS',
  'NOTES_TAKEN' = 'LECTURE_ANALYTICS.NOTES_TAKEN',
  'AVERAGE_WORDS' = 'LECTURE_ANALYTICS.AVERAGE_WORDS',
  'ANNOTATIONS' = 'LECTURE_ANALYTICS.ANNOTATIONS',
}

export enum CUSTOM_SECURITY_APP_ERRORS {
  'PING_ERROR_LOST_CONNECTION' = 'CUSTOM_SECURITY_APP_ERRORS.PING_ERROR_LOST_CONNECTION',
  'INITIALIZATION_ERROR' = 'CUSTOM_SECURITY_APP_ERRORS.INITIALIZATION_ERROR',
}

export enum SECURITY_OVERLAY {
  'PRESENTATION_VIEWER' = 'SECURITY_OVERLAY.PRESENTATION_VIEWER',
  'DOWNLOAD_INSTRUCTIONS' = 'CUSTOM_SECURITY_APP_ERRORS.DOWNLOAD_INSTRUCTIONS',
  'HELP_MESSAGE_1' = 'SECURITY_OVERLAY.HELP_MESSAGE_1',
  'HELP_MESSAGE_2' = 'SECURITY_OVERLAY.HELP_MESSAGE_2',
}

export enum ANALYTICS_TOGGLE {
  'LABEL' = 'ANALYTICS_TOGGLE.LABEL',
  'INCLUDE' = 'ANALYTICS_TOGGLE.INCLUDE',
  'EXCLUDE' = 'ANALYTICS_TOGGLE.EXCLUDE',
}

export enum SERIES_DOCUMENTS {
  'NONE' = 'SERIES_DOCUMENTS.NONE',
}

export enum COURSE_SECURITY_EVENTS {
  'ERROR' = 'COURSE_SECURITY_EVENTS.ERROR',
}
